import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.awt.geom.AffineTransform;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

public class ImageSpinner extends JPanel { // code generated by Chat GPT Testing for Spinning image about its center

    private BufferedImage image;
    private double angle = 0;
    private int centerX, centerY;

    // Create an AffineTransform for rotation
    AffineTransform tx = new AffineTransform();

    public ImageSpinner(BufferedImage image) {
        this.image = image;
        centerX = image.getWidth() / 2;
        centerY = (image.getHeight() / 2);
        tx.translate(50, 50); // new point of origin TRANSLATE THEN ROTATE

        // Start a timer to update the rotation angle
        Timer timer = new Timer(70, e -> {
            angle = Math.toRadians(5); // Adjust rotation speed
            repaint();
        });
        timer.start();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);

        Graphics2D g2d = (Graphics2D) g.create();

        // Clear the background
        g2d.setColor(Color.WHITE);
        g2d.fillRect(0, 0, getWidth(), getHeight());

        tx.rotate(angle, centerX, centerY);

        // Apply the transformation and draw the image
        g2d.drawImage(image, tx, null);

        g2d.dispose();
    }

    public static void main(String[] args) {
        // Load the image
        BufferedImage image = null;
        try {
            image = ImageIO.read(new File("GroupGame/src/images/LTD/cars/orgCar.png"));
        } catch (IOException e) {
            e.printStackTrace();
            System.exit(1);
        }

        // Create and set up the JFrame
        JFrame frame = new JFrame("Image Spinner");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(400, 400);

        // Add the ImageSpinner panel to the frame
        ImageSpinner spinner = new ImageSpinner(image);
        frame.add(spinner);

        // Display the frame
        frame.setVisible(true);
    }
}
